// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// create_sequences
List create_sequences(const std::vector<std::string>& dates, int span, Nullable<int> signal_a, Nullable<int> signal_b);
RcppExport SEXP _myLeverage_create_sequences(SEXP datesSEXP, SEXP spanSEXP, SEXP signal_aSEXP, SEXP signal_bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type dates(datesSEXP);
    Rcpp::traits::input_parameter< int >::type span(spanSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type signal_a(signal_aSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type signal_b(signal_bSEXP);
    rcpp_result_gen = Rcpp::wrap(create_sequences(dates, span, signal_a, signal_b));
    return rcpp_result_gen;
END_RCPP
}

// dca_flows_allocation
void dca_flows_allocation(List input, String name, double flows, int index);
RcppExport SEXP _myLeverage_dca_flows_allocation(SEXP inputSEXP, SEXP nameSEXP, SEXP flowsSEXP, SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type input(inputSEXP);
    Rcpp::traits::input_parameter< String >::type name(nameSEXP);
    Rcpp::traits::input_parameter< double >::type flows(flowsSEXP);
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    dca_flows_allocation(input, name, flows, index);
    return R_NilValue;
END_RCPP
}

// calculate_buy_report
void calculate_buy_report(List input, String name, int index, double trade_count, double trade_price, double market_price);
RcppExport SEXP _myLeverage_calculate_buy_report(SEXP inputSEXP, SEXP nameSEXP, SEXP indexSEXP, SEXP trade_countSEXP, SEXP trade_priceSEXP, SEXP market_priceSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type input(inputSEXP);
    Rcpp::traits::input_parameter< String >::type name(nameSEXP);
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    Rcpp::traits::input_parameter< double >::type trade_count(trade_countSEXP);
    Rcpp::traits::input_parameter< double >::type trade_price(trade_priceSEXP);
    Rcpp::traits::input_parameter< double >::type market_price(market_priceSEXP);
    calculate_buy_report(input, name, index, trade_count, trade_price, market_price);
    return R_NilValue;
END_RCPP
}

// calculate_sell_report
void calculate_sell_report(List input, String name, int index, double trade_count, double trade_price, double market_price, double capital_gains_tax);
RcppExport SEXP _myLeverage_calculate_sell_report(SEXP inputSEXP, SEXP nameSEXP, SEXP indexSEXP, SEXP trade_countSEXP, SEXP trade_priceSEXP, SEXP market_priceSEXP, SEXP capital_gains_taxSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type input(inputSEXP);
    Rcpp::traits::input_parameter< String >::type name(nameSEXP);
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    Rcpp::traits::input_parameter< double >::type trade_count(trade_countSEXP);
    Rcpp::traits::input_parameter< double >::type trade_price(trade_priceSEXP);
    Rcpp::traits::input_parameter< double >::type market_price(market_priceSEXP);
    Rcpp::traits::input_parameter< double >::type capital_gains_tax(capital_gains_taxSEXP);
    calculate_sell_report(input, name, index, trade_count, trade_price, market_price, capital_gains_tax);
    return R_NilValue;
END_RCPP
}

// calculate_total_report
void calculate_total_report(List input, CharacterVector assets, int index);
RcppExport SEXP _myLeverage_calculate_total_report(SEXP inputSEXP, SEXP assetsSEXP, SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type input(inputSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type assets(assetsSEXP);
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    calculate_total_report(input, assets, index);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_myLeverage_create_sequences", (DL_FUNC) &_myLeverage_create_sequences, 4},
    {"_myLeverage_dca_flows_allocation", (DL_FUNC) &_myLeverage_dca_flows_allocation, 4},
    {"_myLeverage_calculate_buy_report", (DL_FUNC) &_myLeverage_calculate_buy_report, 6},
    {"_myLeverage_calculate_sell_report", (DL_FUNC) &_myLeverage_calculate_sell_report, 7},
    {"_myLeverage_calculate_total_report", (DL_FUNC) &_myLeverage_calculate_total_report, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_myLeverage(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
