# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

create_sequences <- function(dates, span, signal_a = NULL, signal_b = NULL) {
    .Call(`_myLeverage_create_sequences`, dates, span, signal_a, signal_b)
}

dca_flows_allocation <- function(input, name, flows, index) {
    invisible(.Call(`_myLeverage_dca_flows_allocation`, input, name, flows, index))
}

calculate_buy_report <- function(input, name, index, trade_count, trade_price, market_price) {
    invisible(.Call(`_myLeverage_calculate_buy_report`, input, name, index, trade_count, trade_price, market_price))
}

calculate_sell_report <- function(input, name, index, trade_count, trade_price, market_price, capital_gains_tax) {
    invisible(.Call(`_myLeverage_calculate_sell_report`, input, name, index, trade_count, trade_price, market_price, capital_gains_tax))
}

calculate_total_report <- function(input, assets, index) {
    invisible(.Call(`_myLeverage_calculate_total_report`, input, assets, index))
}